export const countryList = [
  { title: "United States of America" },
  { title: "European Patent Office" },
  { title: "WIPO" },
  { title: "Japan" },
  { title: "China" },
  { title: "India" },
  { title: "ARIPO" },
  { title: "Argentina" },
  { title: "Austria" },
  { title: "Australia" },
  { title: "Bosnia And Herzegovina" },
  { title: "Belgium" },
  { title: "Bulgaria" },
  { title: "Boliva" },
  { title: "Brazil" },
  { title: "Belarus" },
  { title: "Canada" },
  { title: "Switzerland" },
  { title: "Chile" },
  { title: "Columbia" },
  { title: "Costa Rica" },
  { title: "Czechoslovakia" },
  { title: "Cuba" },
  { title: "Cyprus" },
  { title: "Czech Republic" },
  { title: "East Germany" },
  { title: "Germany" },
  { title: "Denmark" },
  { title: "Dominican Republic" },
  { title: "Algeria" },
  { title: "Eurasian Patent Organization" },
  { title: "Ecuador" },
  { title: "Estonia" },
  { title: "Egypt" },
  { title: "Spain" },
  { title: "Finland" },
  { title: "France" },
  { title: "Great Britain" },
  { title: "GCC" },
  { title: "Georgia" },
  { title: "Greece" },
  { title: "Guatemala" },
  { title: "Hong Kong" },
  { title: "Honduras" },
  { title: "Croatia" },
  { title: "Hungary" },
  { title: "Indonesia" },
  { title: "Ireland" },
  { title: "Israel" },
  { title: "Iceland" },
  { title: "Italy" },
  { title: "Kenya" },
  { title: "South Korea" },
  { title: "Kazakhstan" },
  { title: "Lithuania" },
  { title: "Luxembourg" },
  { title: "Latvia" },
  { title: "Morocco" },
  { title: "Monaco" },
  { title: "Moldova" },
  { title: "Mongolia" },
  { title: "Malta" },
  { title: "Malawi" },
  { title: "Mexico" },
  { title: "Malaysia" },
  { title: "Nicaragua" },
  { title: "Netherlands" },
  { title: "Norway" },
  { title: "New Zealand" },
  { title: "OAPI" },
  { title: "Panama" },
  { title: "Peru" },
  { title: "Philippines" },
  { title: "Poland" },
  { title: "Portugal" },
  { title: "Paraguay" },
  { title: "Romania" },
  { title: "Russia" },
  { title: "Sweden" },
  { title: "Singapore" },
  { title: "Slovenia" },
  { title: "Slovakia" },
  { title: "San Marino" },
  { title: "Soviet Union" },
  { title: "El Salvador" },
  { title: "Tajikistan" },
  { title: "Thailand" },
  { title: "Turkey" },
  { title: "Trinidad" },
  { title: "Taiwan" },
  { title: "Ukranian Republic" },
  { title: "Uruguay" },
  { title: "Uzbekistan" },
  { title: "Venezuela" },
  { title: "Vietnam" },
  { title: "Yugoslavia" },
  { title: "South Africa" },
  { title: "Zambia" },
  { title: "Zimbabwe" },
];
